import React, { useEffect, useState } from "react";
import Head from 'next/head'
import Table from 'react-bootstrap/Table';
import { Button, Form } from "react-bootstrap";
import AsignaturasService from '../../servicios/asignaturas'
import styles from '../../styles/Home.module.css'

export default function Asignatura(props) {
  const [asigId, setAsigId] = useState(null)
  const [asigNombre, setAsigNombre] = useState(null)
  const [datos, setDatos] = useState([])
  const [showEditar, setShowEditar] = useState(false)
  const [showAgregar, setShowAgregar] = useState(false)

  const traerDatos = async () => {
    const datos = await AsignaturasService.getAll()
    setDatos(datos.asignaturas)
  }

  const mostrarNuevaAsig = () => setShowAgregar(true)
  const agregarAsignatura = async (event) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    const data = Object.fromEntries(formData)
    const nombreAsig = data['nombreAsig']
    setShowAgregar(false)

    await AsignaturasService.nuevo(nombreAsig)
    await traerDatos()
  }

  const mostrarEditarAsig = ({ id, nombreAsig }) => {
    console.info('Mostrar', id, nombreAsig)
    setAsigId(id)
    setAsigNombre(nombreAsig)
    setShowEditar(true)
  }
  const editarAsignatura = async (event) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    const data = Object.fromEntries(formData)
    const nombreAsig = data['nombreAsig']
    setShowEditar(false)

    await AsignaturasService.editar({ id: asigId, nombreAsig })

    setAsigId(null)
    setAsigNombre(null)
    await traerDatos()
  }

  const eliminarAsignatura = async (id) => {
    await AsignaturasService.eliminar(id)
    await traerDatos()
  }

  useEffect(() => {
    traerDatos()
  }, [])

    return (
        <div className={styles.container}>
        <Head>
          <title>CICLO III MISIÓN TIC 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h3 className={styles.title} style={{marginBottom:"40px"}}>
            Asignaturas
          </h3>

          <div>
            <button type="button" className="btn btn-primary" onClick={ mostrarNuevaAsig }>
              Crear Asignatura
            </button>

            { showAgregar && (
              <Form onSubmit={ agregarAsignatura }>
                <Form.Group className="mb-3" controlId="nombreAsig">
                  <Form.Label>Nueva asignatura</Form.Label>
                  <Form.Control type="text" placeholder="Nueva asignatura" name="nombreAsig" required />
                </Form.Group>
                <Button variant="primary" type="submit">
                  Agregar
                </Button>
              </Form>
            )}
          </div>

          <Table striped bordered hover style={{width: "600px", marginTop:"20px"}}>
            <thead>
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre de Asignatura</th>
                <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>

               {datos.map((dato, i) =>(
                <tr key={dato.nombreAsig}>
                <th scope="row">{dato.id}</th>
                <td>
                  { asigId !== dato.id && dato.nombreAsig }
                  { (showEditar && asigId === dato.id) && (
                    <Form onSubmit={ editarAsignatura }>
                      <Form.Group className="mb-3" controlId="nombreAsig">
                        <Form.Control required type="text" name="nombreAsig" value={ asigNombre } onChange={ (value) => setAsigNombre(value.target.value) } />
                      </Form.Group>
                      <Button variant="primary" type="submit">
                        Guardar
                      </Button>
                    </Form>
                  )}
                </td>
                <td>
                  <button type="button" className="btn btn-primary" onClick={ () => mostrarEditarAsig(dato) }>
                    Editar
                  </button>

                  <button type="button" className="btn btn-danger" onClick={ () => eliminarAsignatura(dato.id) }>
                    Eliminar
                  </button>
                </td></tr>
               ))}

            </tbody>
            </Table>

            <div>
            <Button href="/admin" className="btn btn-success" style={{marginLeft: "480px"}}>
              Regresar
            </Button>

            </div>

          </main>

        </div>
)
}
