import React, { useEffect, useState } from "react"
import Head from 'next/head'
import Table from 'react-bootstrap/Table';
import { Button, Form } from "react-bootstrap"

import EstudiantesService from '../../servicios/estudiantes'
import GruposService from '../../servicios/grupos'
import styles from '../../styles/Home.module.css'

export default function Estudiantes(props) {
  const [estudianteId, setEstudianteId] = useState(null)
  const [estudianteNuevo, setEstudianteNuevo] = useState(null)
  const [datos, setDatos] = useState([])
  const [datosGrupo, setDatosGrupo] = useState([])
  const [showEditar, setShowEditar] = useState(false)
  const [showAgregar, setShowAgregar] = useState(false)

  const traerDatos = async () => {
    const datos = await EstudiantesService.getAll()
    const grupos = await GruposService.getAll()
    setDatos(datos.estudiantes)
    setDatosGrupo(grupos.grupos)
  }

  const mostrarNuevoEstudiante = () => setShowAgregar(true)
  const agregarEstudiante = async (event) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    const data = Object.fromEntries(formData)
    const { nombres, apellidos, username, pass, grupoId } = data

    if (nombres && apellidos && username && pass && grupoId && grupoId !== '0') {
      setShowAgregar(false)
      await EstudiantesService.nuevo(data)
      await traerDatos()
    }
  }

  const mostrarEditarEstudiante = (estudiante) => {
    setEstudianteId(estudiante.id)
    setEstudianteNuevo({
      nombres: estudiante.nombres,
      apellidos: estudiante.apellidos,
      username: estudiante.username,
    })
    setShowEditar(true)
  }
  const editarEstudiante = async (id) => {
    setShowEditar(false)
    await EstudiantesService.editar({ id, ...estudianteNuevo })

    setEstudianteId(null)
    setEstudianteNuevo(null)
    await traerDatos()
  }

  const eliminarEstudiante = async (id) => {
    await EstudiantesService.eliminar(id)
    await traerDatos()
  }

  useEffect(() => {
    traerDatos()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>CICLO III MISIÓN TIC 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title} style={{marginBottom:"40px"}}>
          Estudiantes
        </h3>

        <div>
          <button type="button" className="btn btn-primary" onClick={ mostrarNuevoEstudiante }>
            Crear Estudiante
          </button>

          { showAgregar && (
            <Form onSubmit={ agregarEstudiante }>
              <Form.Group className="mb-3" controlId="nombres">
                <Form.Label>Nombres</Form.Label>
                <Form.Control type="text" placeholder="Nombres" name="nombres" required />
              </Form.Group>
              <Form.Group className="mb-3" controlId="apellidos">
                <Form.Label>Apellidos</Form.Label>
                <Form.Control type="text" placeholder="Apellidos" name="apellidos" required />
              </Form.Group>
              <Form.Group className="mb-3" controlId="username">
                <Form.Label>Usuario</Form.Label>
                <Form.Control type="text" placeholder="Usuario" name="username" required />
              </Form.Group>
              <Form.Group className="mb-3" controlId="pass">
                <Form.Label>Contraseña</Form.Label>
                <Form.Control type="password" placeholder="Contraseña" name="pass" required />
              </Form.Group>
              <Form.Group className="mb-3" controlId="grupoId">
                <Form.Label>Grupo</Form.Label>
                <Form.Select aria-label="Seleccione un grupo" name="grupoId" required>
                  <option value="0">Seleccione un grupo</option>
                  { datosGrupo.map((grupo) => (
                    <option key={ grupo.nomgrupo } value={ grupo.id }>{ grupo.nomgrupo }</option>
                  )) }
                </Form.Select>
              </Form.Group>
              <Button variant="primary" type="submit">
                Agregar
              </Button>
            </Form>
          )}
        </div>

        <Table striped bordered hover style={{ width: "900px", marginTop:"20px" }}>
          <thead>
            <tr>
              <th scope="col">No.</th>
              <th scope="col">Apellidos</th>
              <th scope="col">Nombres</th>
              <th scope="col">Usuario</th>
              <th scope="col">Grupo</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            { !!datos && datos.map((dato, i) => (
              <tr key={dato.nombres}>
                <th scope="row">{ dato.id }</th>
                <td>
                  { estudianteId !== dato.id && dato.nombres }
                  { (showEditar && estudianteId === dato.id) && (
                    <input
                      required
                      type="text"
                      className="form-control mt-1"
                      placeholder="Digite sus nombres"
                      id="nombres"
                      name="nombres"
                      value={ estudianteNuevo.nombres }
                      onChange={ (value) => setEstudianteNuevo({ ...estudianteNuevo, nombres: value.target.value }) }
                    />
                  )}
                </td>
                <td>
                  { estudianteId !== dato.id && dato.apellidos }
                  { (showEditar && estudianteId === dato.id) && (
                    <input
                      required
                      type="text"
                      className="form-control mt-1"
                      placeholder="Digite sus apellidos"
                      id="apellidos"
                      name="apellidos"
                      value={ estudianteNuevo.apellidos }
                      onChange={ (value) => setEstudianteNuevo({ ...estudianteNuevo, apellidos: value.target.value }) }
                    />
                  )}
                </td>
                <td>
                  { estudianteId !== dato.id && dato.username }
                  { (showEditar && estudianteId === dato.id) && (
                    <input
                      required
                      type="text"
                      className="form-control mt-1"
                      placeholder="Digite su usuario"
                      id="username"
                      name="username"
                      value={ estudianteNuevo.username }
                      onChange={ (value) => setEstudianteNuevo({ ...estudianteNuevo, username: value.target.value }) }
                    />
                  )}
                </td>
                <td>{dato.grupos[0].nomgrupo}</td>
                <td>
                  { estudianteId !== dato.id && (
                    <>
                      <button type="button" className="btn btn-primary" onClick={ () => mostrarEditarEstudiante(dato) }>
                        Editar
                      </button>
                      <button type="button" className="btn btn-danger" onClick={ () => eliminarEstudiante(dato.id) }>
                        Eliminar
                      </button>
                    </>
                  ) }
                  { (showEditar && estudianteId === dato.id) && (
                    <button type="button" className="btn btn-primary" onClick={ () => editarEstudiante(dato.id) }>
                      Guardar
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </Table>

        <div>
          <Button href="/admin" className="btn btn-success" style={{marginLeft: "480px"}}>
            Regresar
          </Button>
        </div>
      </main>
    </div>
  )
}
