import React, { useEffect, useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Table from 'react-bootstrap/Table';
import { Button } from "react-bootstrap";
import { useRouter } from "next/router";
import styles from '../../../styles/Home.module.css'
import EstudiantesService from '../../../servicios/estudiantes'

export default function Estudiante(props) {
  const router = useRouter()
  const { estudianteId } = router.query

  const [estudiante, setEstudiante] = useState(null)

  const traerDatos = async () => {
    if (estudianteId) {
      const datos = await EstudiantesService.find(estudianteId)
      setEstudiante(datos.estudiantes)
    }
  }

  useEffect(() => {
    traerDatos()
  }, [estudianteId])

  return (
    <div className={styles.container}>
      <Head>
        <title>CICLO III MISIÓN TIC 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Bienvenido Estudiante { `${estudiante?.nombres} ${estudiante?.apellidos}` }
        </h3>

        <p className={styles.description}>
          A continuación encuentra las calificaciones registradas por su docente en cada una de las asignaturas matriculadas:
        </p>

        <Table striped bordered hover>
          <thead>
              <tr>
              <th scope="col">Asignatura</th>
              <th scope="col">Nota 1</th>
              <th scope="col">Nota 2</th>
              <th scope="col">Nota 3</th>
              <th scope="col">Nota 4</th>
              <th scope="col">Nota 5</th>
              <th scope="col">Nota Final</th>
              </tr>
          </thead>
          <tbody>
            { !!estudiante?.asignaturas && estudiante.asignaturas.map(asignatura => {
              const nota = estudiante?.notas?.find(nota => nota.asignaturaId === asignatura.id)

              return (
                <tr key={ asignatura.nombreAsig }>
                  <th scope="row">{ asignatura.nombreAsig }</th>
                  <td>{ nota?.nota1 || 0 }</td>
                  <td>{ nota?.nota2 || 0 }</td>
                  <td>{ nota?.nota3 || 0 }</td>
                  <td>{ nota?.nota4 || 0 }</td>
                  <td>{ nota?.nota5 || 0 }</td>
                  <td>{ nota?.notaFinal || 0 }</td>
                </tr>
              )
            }) }
          </tbody>
        </Table>
        <div>
        <Button href="/login" className="btn btn-success" style={{marginLeft: "480px"}}>
          Salir
        </Button>

        </div>

        </main>


      </div>
  )
}
