import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Table from 'react-bootstrap/Table';
import { Button } from "react-bootstrap";


export default function Docente(props){
    const datos1=[{
        apellido:"Garzón Liberato", 
        nombre:"Julián Favián",
        docum:"1012321027"
    }, {
        apellido:"Pinzón Gómez", 
        nombre:"Ramiro Alfonso",
        docum:"80729682"
    }, {
        nombre:"Jimmy Orlando", 
        apellido:"Salcedo Méndez",
        docum:"93395199"
    }]

    const datos2=[{
        apellido:"Molina Salcedo", 
        nombre:"Andres",
        docum:"105467389"
    }, {
        apellido:"Perez Sosa", 
        nombre:"Ximena Lorena",
        docum:"65478392"
    }, {
        nombre:"Rosendo", 
        apellido:"Méndez Ruiz",
        docum:"93456378"
    }]

    const datos3=[{
        apellido:"Castaño Poveda", 
        nombre:"Leonel",
        docum:"123895674"
    }, {
        apellido:"Alvarez Cano", 
        nombre:"Alfredo",
        docum:"45671234"
    }, {
        nombre:"Sandra Milena", 
        apellido:"Caro Martinez",
        docum:"38645378"
    }]
    return (
        <div className={styles.container}>
        <Head>
          <title>CICLO III MISIÓN TIC 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main1}>
          <h3 className={styles.title}>
            Bienvenido Docente Edissón Caicedo
          </h3>
  
          <p className={styles.description}>
            A continuación encuentra los estudiantes a su cargo en Desarrollo de Software Grupo 04:
          </p>

          <Table striped bordered hover>
            <thead>
                <tr>
                <th scope="col">No.</th>
                <th scope="col">Apellidos</th>
                <th scope="col">Nombres</th>
                <th scope="col">Doc.Identidad</th>
                <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                
               {datos1.map((dato, i) =>(
                <tr key={dato.docum}>
                <th scope="row">{i+1}</th>
                <td>{dato.apellido}</td>
                <td>{dato.nombre}</td>
                <td>{dato.docum}</td>
                <td>
                <button type="button" className="btn btn-primary" >
                Calificar
                </button>
                </td></tr> 
               ))}
               
            </tbody>
            </Table>

            <p className={styles.description}>
            A continuación encuentra los estudiantes a su cargo en Desarrollo de Software Grupo 05:
          </p>

          <Table striped bordered hover>
            <thead>
                <tr>
                <th scope="col">No.</th>
                <th scope="col">Apellidos</th>
                <th scope="col">Nombres</th>
                <th scope="col">Doc.Identidad</th>
                <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
            {datos2.map((dato, i) =>(
                <tr key={dato.docum}>
                <th scope="row">{i+1}</th>
                <td>{dato.apellido}</td>
                <td>{dato.nombre}</td>
                <td>{dato.docum}</td>
                <td>
                <button type="button" className="btn btn-primary" >
                Calificar
                </button>
                </td></tr> 
               ))}
            </tbody>
            </Table>
            <p className={styles.description}>
            A continuación encuentra los estudiantes a su cargo en Desarrollo de Software Grupo 06:
          </p>

          <Table striped bordered hover style={{marginBottom:"100px"}}>
            <thead>
                <tr>
                <th scope="col">No.</th>
                <th scope="col">Apellidos</th>
                <th scope="col">Nombres</th>
                <th scope="col">Doc.Identidad</th>
                <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
            {datos3.map((dato, i) =>(
                <tr key={dato.docum}>
                <th scope="row">{i+1}</th>
                <td>{dato.apellido}</td>
                <td>{dato.nombre}</td>
                <td>{dato.docum}</td>
                <td>
                <button type="button" className="btn btn-primary" >
                Calificar
                </button>
                </td></tr> 
               ))}
            </tbody>
            </Table>
            <div>
            
            <Button href="/login" className="btn btn-success" style={{marginLeft: "480px"}}>
              Salir
            </Button> 
               
            </div>
          </main>

        </div>
    );
}