import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Table from 'react-bootstrap/Table';
import { Button } from "react-bootstrap";

export default function Estudiante(props){
    return (
        <div className={styles.container}>
        <Head>
          <title>CICLO III MISIÓN TIC 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h3 className={styles.title}>
            Bienvenido Estudiante Jimmy Orlando Salcedo Méndez
          </h3>
  
          <p className={styles.description}>
            A continuación encuentra las calificaciones registradas por su docente en cada una de las asignaturas matriculadas:
          </p>

          <Table striped bordered hover>
            <thead>
                <tr>
                <th scope="col">Asignatura</th>
                <th scope="col">Nota 1</th>
                <th scope="col">Nota 2</th>
                <th scope="col">Nota 3</th>
                <th scope="col">Nota 4</th>
                <th scope="col">Nota 5</th>
                <th scope="col">Nota Final</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <th scope="row">Desarrollo de Software</th>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                </tr>
                <tr>
                <th scope="row">Inglés III</th>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                </tr>
                <tr>
                <th scope="row">Coach III</th>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                <td>5.0</td>
                </tr>
            </tbody>
            </Table>
            <div>
            <Button href="/login" className="btn btn-success" style={{marginLeft: "480px"}}>
              Salir
            </Button> 
               
            </div>
          
          </main>

        
        </div>
)
}
