import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CICLO III MISIÓN TIC 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido al gestor de notas Ciclo III  <a href="https://www.misiontic2022.gov.co/portal/">Misión TIC 2022!</a>
        </h1>

        <p className={styles.description}>
          Por favor autenticarse{' '}
          <Link href="/login">Aquí</Link>
        </p>

        
      </main>

      
    </div>
  )
}
